### ISSUE TITLE
Alternative to Google Drive

### ISSUE THREAD

**Issue by mchamberland** [brianmanderson/DicomTemplateMakerCSharp#4]
Google Drive is blocked on my work domain. In fact, most shared drives (Google Drive, Dropbox, etc.) are blocked. 

Any chance the program could be hosted on a website and not on a shared drive?

I have a workaround; this is just a suggestion to make it easier for other people in my situation.

**Comment by brianmanderson** [comment]
Hello! Sorry for the delayed response.

That's a great suggestion, especially considering so many institutions block Google drive. I don't have much experience with hosting a website.

Open to workarounds and recommendations!

**Comment by mchamberland** [comment]
I've never used the feature myself, but perhaps using the GitHub release feature? It seems like you can include downloadable binaries to releases. See for example here: https://github.com/nrc-cnrc/EGSnrc/releases/tag/v2023

**Comment by brianmanderson** [comment]
Hey! Sorry for the long delay in this, but I've uploaded a release for installation and the local binaries!

**Comment by brianmanderson** [comment]
Hey! Thanks for the great idea. I've uploaded a release for installation and the local binaries!
